### ISSUE TITLE
Link to the online calculator is broken

### ISSUE THREAD

**Issue by rany2** [MaZderMind/genmask#1]
Thanks for this calculator, it really helped me understand this macro better and update old code.

I just wanted to let you know that the link to the page is off, while https://mazdermind.de/genmask/ doesn't work; https://mazdermind.de/genmask/index.html does. So I assume you didn't have the right `index` set in nginx.

**Comment by MaZderMind** [comment]
Ooof, your right. I moved servers inbetween and missed that. Fixed!
